name: CI with Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build/test steps go here (e.g., SonarQube, testing, etc.)
      # ...

    # Always send the email regardless of the outcome

      - name: Download CNES Report
        run: |
             curl -u squ_29d0bc4bb29df0034ce7c7e28bd64954cd1edb74: "http://13.201.109.77:9000/api/cnesreport/report?key=acc1&format=docx" --output cnes-report.docx

      - name: Upload CNES Report
        uses: actions/upload-artifact@v3
        with:
            name: CNES Report
            path: cnes-report.docx
          
      - name: Send email on success or failure
        if: always()  # ensures that this step runs no matter what
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}      # app password from google account
          subject: "GitHub Action Pipeline Status - ${{ job.status }}"
          body: |
            The GitHub Action for your project has completed.
          
            Status: ${{ job.status }} 
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}

            Check the details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          secure: true
          attachments: cnes-report.zip
