name: CI with Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build/test steps go here (e.g., SonarQube, testing, etc.)
      # ...

    # Always send the email regardless of the outcome

      - name: Download SonarQube Report (JSON)
        run: |
          curl -u sqp_b6f45c34804349735cd4a0f84d14d800703e8f90: \
          "http://13.201.109.77:9000/api/issues/search?projectKey=test" \
          -o sonarqube-report.json
      - name: Prettify JSON Report
        run: |
          cat sonarqube-report.json | jq '.' > pretty-sonarqube-report.json
      - name: Upload Pretty Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pretty-sonarqube-report
          path: pretty-sonarqube-report.json
          
      - name: Send email on success or failure
        if: always()  # ensures that this step runs no matter what
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}   # smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}      # app password from google account
          subject: "GitHub Action Pipeline Status - ${{ job.status }}"
          body: |
            The GitHub Action for your project has completed.
          
            Status: ${{ job.status }} 
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}

            Check the details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          secure: true
          attachments: pretty-sonarqube-report.json
